version: '2'

services:
  app1:
    image: php:7.4-apache
    environment:
      - VIRTUAL_HOST=demo.miperu.org
      - VIRTUAL_PORT=9000
    networks:
      - test_network
      
networks:
    test_network:
        external: true
